---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: udp-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-server
  template:
    metadata:
      labels:
        app: udp-server
    spec:
      containers:
      - name: udp-server
        image: indx0/udp-server:server
        ports:
        - containerPort: 8080
          protocol: UDP
        volumeMounts:
        - name: server-data-volume
          mountPath: /app/data
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
      volumes:
      - name: server-data-volume
        persistentVolumeClaim:
          claimName: udp-server-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: udp-server
spec:
  selector:
    app: udp-server
  ports:
    - protocol: UDP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-client
  template:
    metadata:
      labels:
        app: udp-client
    spec:
      containers:
      - name: udp-client
        image: indx0/udp-server:client
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"