services:
  udp-server:
    build: ./server
    image: udp-server
    container_name: udp_echo_container
    ports:
      - "8080:8080/udp"      
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    networks:
      - my_net
  udp-client:
    build: ./client
    image: udp-client
    container_name: udp_client_container
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    networks:
      - my_net

networks:
  my_net:
    driver: bridge